version: "3"

services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - challenge-network
    ports:
      - "8080:80"

  app:
    build:
      context: ./app
    command: node index.js
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - challenge-network
    tty: true
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - challenge-network

networks:
  challenge-network:
    driver: bridge
